<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>NekoStrap.Smoke</AssemblyName>
    <RootNamespace>NekoStrap.Smoke</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NekoStrap.Wpf\NekoStrap.Wpf.csproj" />
    <ProjectReference Include="..\NekoStrap.Core\NekoStrap.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="System.IO" />
    <Using Include="System.Net.Http" />
  </ItemGroup>

</Project>
